spring:
  profiles:
    active: local, testdata
  config:
    import: ""

#  rabbitmq:
#    host: ${rabbitmq_host}
#    port: ${rabbitmq_port}
#    username: ${rabbitmq_username}
#    password: ${rabbitmq_password}

  data:
    mongodb:
      uri: ${mongodb_uri}

  cloud:
    config:
      uri: http://localhost:8888
      request-connect-timeout: 5000
      request-read-timeout: 5000
      fail-fast: false
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, bus-refresh

